name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: 'euturial'
          password: ${{secrets.SECRETE_DOCKER_HUB}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          tags: 'euturial/apifcg:latest'
          push: true


                
      
            
